# Generated by Django 5.0.3 on 2024-03-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='article',
            name='flags',
            field=models.IntegerField(default=0),
        ),
    ]
