# Generated by Django 5.0.3 on 2024-03-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_posts', '0004_delete_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
