# Generated by Django 5.0.3 on 2024-03-21 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_posts', '0008_alter_report_article_alter_report_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='created_by',
            new_name='reported_by',
        ),
    ]
